name: "Install KaaS"
description: "Install KaaS on the Runner for use in later steps and utilize kaas-cli push/pull of KCFGs"
runs:
  using: "composite"
  steps:
    - name: "Install Python3.10 or Greater"
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: "Install KaaS"
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/install-kaas.sh